CREATE DATABASE contodo; --\c contodo

CREATE TABLE items(
  item_id SERIAL PRIMARY KEY,
  title VARCHAR(30),
  content VARCHAR(255)
);

ALTER TABLE items ADD COLUMN color VARCHAR(7);

ALTER TABLE items ADD COLUMN pinned BOOLEAN DEFAULT FALSE;
ALTER TABLE items ADD COLUMN importance INT CHECK (importance BETWEEN 1 AND 3) DEFAULT 3;